development:
  adapter: postgresql
  encoding: unicode
  database: testDemo_test
  pool: 5
  username: c238
  password: password

test:
   adapter: postgresql
   encoding: unicode
   database: testDemo_test
   pool: 5
   username: c238
   password: password


production:
   adapter: postgresql
   encoding: unicode
   database: testDemo_test
   pool: 5
   username: c238
   password: password
